/** Demo asset + cycle count data for NFC deep links */
window.ASSET_DATA = {
  requestFormUrl: "https://forms.office.com/r/wQM2EHkQBg",
  assets: [
    {
      id: "AST-001",
      name: "Portable Ultrasound Unit",
      category: "Medical Equipment",
      status: "In Service",
      location: "Building A · Room 214",
      department: "Radiology",
      serialNumber: "US-88421-A",
      manufacturer: "SonoTech",
      model: "ClearVue 12",
      purchaseDate: "2023-03-14",
      custodian: "Jordan Lee",
      nfcUid: "04:A1:B2:C3:D4:E5:F6",
      description:
        "Mobile ultrasound cart used for bedside diagnostics. NFC tag affixed to the main chassis.",
      cycleCount: {
        lastCounted: "2026-06-28",
        nextDue: "2026-07-28",
        expectedQty: 1,
        countedQty: 1,
        variance: 0,
        countStatus: "Matched",
        countedBy: "Morgan Chen",
        binLocation: "RAD-CART-03",
        notes: "Tag scanned on unit; condition good.",
      },
    },
    {
      id: "AST-002",
      name: "Infusion Pump Rack",
      category: "Medical Equipment",
      status: "In Service",
      location: "Building B · ICU Wing",
      department: "Critical Care",
      serialNumber: "IP-55210-C",
      manufacturer: "MedFlow",
      model: "InfusePro X4",
      purchaseDate: "2022-11-02",
      custodian: "Avery Patel",
      nfcUid: "04:11:22:33:44:55:66",
      description:
        "Four-channel infusion pump station. Scan the NFC tag on the side panel for asset details.",
      cycleCount: {
        lastCounted: "2026-06-15",
        nextDue: "2026-07-15",
        expectedQty: 1,
        countedQty: 1,
        variance: 0,
        countStatus: "Matched",
        countedBy: "Sam Rivera",
        binLocation: "ICU-EQ-12",
        notes: "Verified serial plate matches record.",
      },
    },
    {
      id: "AST-003",
      name: "Laptop · Field Service",
      category: "IT Asset",
      status: "Checked Out",
      location: "Field · Van 7",
      department: "Facilities",
      serialNumber: "LT-9K2M8P",
      manufacturer: "Lenovo",
      model: "ThinkPad T14 Gen 4",
      purchaseDate: "2024-01-20",
      custodian: "Casey Nguyen",
      nfcUid: "04:AA:BB:CC:DD:EE:01",
      description:
        "Encrypted field laptop for maintenance work orders. NFC sticker under the keyboard deck.",
      cycleCount: {
        lastCounted: "2026-07-01",
        nextDue: "2026-08-01",
        expectedQty: 1,
        countedQty: 0,
        variance: -1,
        countStatus: "Variance",
        countedBy: "Taylor Brooks",
        binLocation: "IT-LOAN-02",
        notes: "Not found at home bay; assigned to Van 7 — follow up.",
      },
    },
    {
      id: "AST-004",
      name: "Calibration Multimeter",
      category: "Test Equipment",
      status: "In Calibration",
      location: "Building C · Metrology Lab",
      department: "Quality",
      serialNumber: "MM-77301",
      manufacturer: "Fluke",
      model: "8846A",
      purchaseDate: "2021-08-09",
      custodian: "Riley Okonkwo",
      nfcUid: "04:77:88:99:AA:BB:CC",
      description:
        "Precision digital multimeter used for instrument calibration. NFC tag on the carrying case.",
      cycleCount: {
        lastCounted: "2026-06-20",
        nextDue: "2026-07-20",
        expectedQty: 1,
        countedQty: 1,
        variance: 0,
        countStatus: "Matched",
        countedBy: "Jamie Ortiz",
        binLocation: "MET-SHELF-A2",
        notes: "In cal lab queue; asset present.",
      },
    },
    {
      id: "AST-005",
      name: "Mobile Crash Cart",
      category: "Medical Equipment",
      status: "In Service",
      location: "Building A · ED Bay 3",
      department: "Emergency",
      serialNumber: "CC-12055",
      manufacturer: "LifeLine",
      model: "RapidResponse 300",
      purchaseDate: "2020-05-18",
      custodian: "Quinn Morales",
      nfcUid: "04:DE:AD:BE:EF:00:05",
      description:
        "Emergency crash cart with defibrillator dock. NFC tag mounted on the top drawer rail.",
      cycleCount: {
        lastCounted: "2026-07-10",
        nextDue: "2026-08-10",
        expectedQty: 1,
        countedQty: 1,
        variance: 0,
        countStatus: "Matched",
        countedBy: "Alex Kim",
        binLocation: "ED-BAY-03",
        notes: "Seal intact; counted during shift change.",
      },
    },
  ],
};

window.getAssetById = function getAssetById(id) {
  return window.ASSET_DATA.assets.find(
    (a) => a.id.toLowerCase() === String(id || "").toLowerCase()
  );
};
